version: "3.7"
services:
  btc:
    build: ./bitcoind
    image: btc:latest
    labels:
      - "description: bitcoin"
    ports: 
      - 10000:10000
    environment:
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=btc
      - EXEC=bitcoind
    volumes:
      - /Users/eric/tmp/btc/${ENV}_data:/root/${ENV}_data:rw
  bch:
    build: ./btc-family
    image: bch:latest
    labels:
      - "description: bitcoin-abc"
    ports: 
      - 11000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/Bitcoin-ABC/bitcoin-abc/releases/download/v0.19.6/bitcoin-abc-0.19.6-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=bch
      - EXEC=bitcoind
    volumes:
      - /Users/eric/tmp/bch/${ENV}_data:/root/${ENV}_data:rw
  bsv:
    build: ./btc-family
    image: bsv:latest
    labels:
      - "description: bitcoin-sv"
    ports: 
      - 12000:10000
    environment:
      - DOWNLOAD_URL=https://download.bitcoinsv.io/bitcoinsv/0.1.1/bitcoin-sv-0.1.1-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=bsv
      - EXEC=bitcoind
    volumes:
      - /Users/eric/tmp/bsv/${ENV}_data:/root/${ENV}_data:rw
  btcp:
    build: ./btcp
    image: btcp:latest
    labels:
      - "description: bitcoin-private"
    ports: 
      - 13000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/BTCPrivate/BitcoinPrivate/releases/download/1.0.13/btcp_1.0.13-linux.zip
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=btcp
      - EXEC=btcpd
    volumes:
      - /Users/eric/tmp/btcp/${ENV}_data:/root/${ENV}_data:rw
  btg:
    build: ./btc-family
    image: btg:latest
    labels:
      - "description: bitcoin-gold"
    ports: 
      - 14000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/BTCGPU/BTCGPU/releases/download/v0.15.2/bitcoin-gold-0.15.2-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=btg
      - EXEC=bgoldd
    volumes:
      - /Users/eric/tmp/btg/${ENV}_data:/root/${ENV}_data:rw
  cnx:
    build: ./btc-family
    image: cnx:latest
    labels:
      - "description: cryptonex"
    ports: 
      - 15000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/Cryptonex/release/raw/master/cryptonex-daemon.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test1
      - RPC_ALLOW_IP=*.*.*.*
      - SYMBOL=cnx
      - EXEC=cryptonexd
    volumes:
      - /Users/eric/tmp/cnx/${ENV}_data:/root/${ENV}_data:rw
  dash:
    build: ./btc-family
    image: dash:latest
    labels:
      - "description: dashcore"
    ports: 
      - 16000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/dashpay/dash/releases/download/v0.14.0.0/dashcore-0.14.0.0-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=dash
      - EXEC=dashd
    volumes:
      - /Users/eric/tmp/dash/${ENV}_data:/root/${ENV}_data:rw
  doge:
    build: ./btc-family
    image: doge:latest
    labels:
      - "description: dogecoin"
    ports: 
      - 17000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/dogecoin/dogecoin/releases/download/v1.14-rc-1/dogecoin-1.14.0-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=doge
      - EXEC=dogecoind
    volumes:
      - /Users/eric/tmp/doge/${ENV}_data:/root/${ENV}_data:rw
  ltc:
    build: ./btc-family
    image: ltc:latest
    labels:
      - "description: litecoin"
    ports: 
      - 18000:10000
    environment:
      - DOWNLOAD_URL=https://download.litecoin.org/litecoin-0.17.1/linux/litecoin-0.17.1-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=ltc
      - EXEC=litecoind
    volumes:
      - /Users/eric/tmp/ltc/${ENV}_data:/root/${ENV}_data:rw
  mona:
    build: ./btc-family
    image: mona:latest
    labels:
      - "description: mona"
    ports: 
      - 19000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/monacoinproject/monacoin/releases/download/monacoin-0.15.1/monacoin-0.15.1-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=mona
      - EXEC=monacoind
    volumes:
      - /Users/eric/tmp/mona/${ENV}_data:/root/${ENV}_data:rw
  omni:
    build: ./btc-family
    image: omni:latest
    labels:
      - "description: omni-usdt"
    ports: 
      - 20000:10000
    environment:
      - DOWNLOAD_URL=https://github.com/OmniLayer/omnicore/releases/download/v0.5.0/omnicore-0.5.0-x86_64-linux-gnu.tar.gz
      - ENV=${ENV}
      - RPC_PORT=10000
      - RPC_USER=test
      - RPC_PASSWORD=test
      - RPC_ALLOW_IP=0.0.0.0/0
      - SYMBOL=usdt
      - EXEC=omnicored
    volumes:
      - /Users/eric/tmp/omni/${ENV}_data:/root/${ENV}_data:rw

  # bcd:
  #   build: ./btc-family
  #   image: bcd:latest
  #   labels:
  #     - "description: bitcoin-diamond"
  #   ports: 
  #     - 21000:10000
  #   environment:
  #     - DOWNLOAD_URL=https://github.com/eveybcd/BitcoinDiamond/releases/download/v1.3.0/bitcoindiamond-1.3.0-x86_64-linux-gnu.tar.gz
  #     - ENV=${ENV}
  #     - RPC_USER=test
  #     - RPC_PASSWORD=test
  #     - RPC_ALLOW_IP=0.0.0.0/0
  #     - SYMBOL=bcd
  #     - EXEC=bitcoindiamondd
  #   volumes:
  #     - /Users/eric/tmp/bcd/${ENV}_data:/root/${ENV}_data:rw